// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/brave-logos/DotI.tsx": () => import("../components/mockups/brave-logos/DotI.tsx"),
  "./components/mockups/brave-logos/Monogram.tsx": () => import("../components/mockups/brave-logos/Monogram.tsx"),
  "./components/mockups/brave-logos/SparkV.tsx": () => import("../components/mockups/brave-logos/SparkV.tsx"),
  "./components/mockups/brave-logos/SplitVi.tsx": () => import("../components/mockups/brave-logos/SplitVi.tsx"),
  "./components/mockups/brave-logos/Stamp.tsx": () => import("../components/mockups/brave-logos/Stamp.tsx"),
  "./components/mockups/brave-logos/Surge.tsx": () => import("../components/mockups/brave-logos/Surge.tsx")
};
